# Generated by Django 4.0.3 on 2022-03-21 18:37

import LaunchDataTracker.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaunchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liftoff_time', models.DateTimeField(verbose_name='Est. Liftoff Time')),
                ('active_launch', models.BooleanField(verbose_name='Launch Active')),
                ('flight_computer', models.CharField(max_length=255, verbose_name='Payload ID')),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_received', models.DateTimeField(verbose_name='Time Received')),
                ('telemetry', models.JSONField(default=LaunchDataTracker.models.TelemetryPacket._default_packet, verbose_name='Raw Telemetry')),
                ('launch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LaunchDataTracker.launchinfo')),
            ],
        ),
    ]
