# Generated by Django 4.0.3 on 2022-03-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaunchDataTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchinfo',
            name='liftoff_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Est. Liftoff Time'),
        ),
    ]
