# Generated by Django 4.0.3 on 2022-03-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaunchDataTracker', '0002_alter_launchinfo_liftoff_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchinfo',
            name='liftoff_time',
            field=models.DateTimeField(verbose_name='Est. Liftoff Time'),
        ),
        migrations.AlterField(
            model_name='telemetrypacket',
            name='time_received',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time Received'),
        ),
    ]
