# Generated by Django 4.0.3 on 2022-03-22 17:42

import LaunchDataTracker.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LaunchDataTracker', '0003_alter_launchinfo_liftoff_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255, verbose_name='Payload ID')),
                ('features', models.JSONField(default=LaunchDataTracker.models.Payload._default_features, verbose_name='Feature Set')),
            ],
        ),
        migrations.AlterField(
            model_name='launchinfo',
            name='flight_computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LaunchDataTracker.payload'),
        ),
    ]
