# Generated by Django 4.0.3 on 2022-03-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaunchDataTracker', '0004_payload_alter_launchinfo_flight_computer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeripheralStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddConstraint(
            model_name='launchinfo',
            constraint=models.UniqueConstraint(condition=models.Q(('active_launch', True)), fields=('flight_computer',), name='unique_active_launch'),
        ),
        migrations.AddField(
            model_name='peripheralstatus',
            name='peripheral_name',
            field=models.ManyToManyField(to='LaunchDataTracker.launchinfo'),
        ),
    ]
