# Generated by Django 4.0.3 on 2022-03-28 20:09

import LaunchDataTracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaunchDataTracker', '0005_peripheralstatus_launchinfo_unique_active_launch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peripheralstatus',
            old_name='peripheral_name',
            new_name='launch',
        ),
        migrations.AddField(
            model_name='peripheralstatus',
            name='p_data',
            field=models.JSONField(default=LaunchDataTracker.models.PeripheralStatus._default_status, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='peripheralstatus',
            name='p_id',
            field=models.CharField(default='dumb', max_length=255, verbose_name='Peripheral ID'),
            preserve_default=False,
        ),
    ]
