# Generated by Django 4.0.3 on 2022-03-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaunchDataTracker', '0006_rename_peripheral_name_peripheralstatus_launch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peripheralstatus',
            name='p_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Peripheral ID'),
        ),
    ]
