# Generated by Django 4.0.3 on 2022-03-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaunchDataTracker', '0007_alter_peripheralstatus_p_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payload',
            name='model_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Payload ID'),
        ),
    ]
