# Generated by Django 4.0.3 on 2022-04-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaunchDataTracker', '0009_payload_connected_peripheralstatus_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='launchinfo',
            name='launch_site',
            field=models.CharField(default='Test Launch', max_length=255, verbose_name='Launch Site'),
            preserve_default=False,
        ),
    ]
