# Generated by Django 4.0.3 on 2022-04-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaunchDataTracker', '0010_launchinfo_launch_site'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='launchinfo',
            name='unique_active_launch',
        ),
        migrations.AddField(
            model_name='launchinfo',
            name='misc_info',
            field=models.JSONField(default={}, verbose_name='Miscellaneous Info'),
            preserve_default=False,
        ),
    ]
